# Generated by Django 3.2 on 2021-05-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampoint',
            name='weekScore',
            field=models.IntegerField(default=0),
        ),
    ]
