# Generated by Django 3.2 on 2021-05-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeknumber', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentPass', models.IntegerField(default=0)),
                ('attendancePass', models.IntegerField(default=0)),
                ('lecturePass', models.IntegerField(default=0)),
                ('AdditionalPoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklion.additionalpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklion.team')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklion.week')),
            ],
        ),
        migrations.AlterField(
            model_name='additionalpoint',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklion.week'),
        ),
        migrations.AlterField(
            model_name='score',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checklion.week'),
        ),
    ]
