# Generated by Django 3.2 on 2021-05-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklion', '0002_auto_20210504_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampoint',
            name='AdditionalPoint',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AdditionalPoint',
        ),
    ]
