# Generated by Django 3.2 on 2021-05-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklion', '0003_auto_20210504_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Status',
        ),
    ]
